window_height = 720
window_width = 1280
gamma = 1.5
player_speed = 8.0
player_light_intensity = 20.0
sunlight_intensity = 600.0
mouse_sensitivity = 8.0

exit = escape
move_cam_up = r
move_cam_down = f
move_cam_left = a
move_cam_right = d
move_cam_forward = w
move_cam_backward = s
toggle_light = q
